---
- name: run gitflow installer  # noqa no-changed-when command-instead-of-shell
  ansible.builtin.shell:
    cmd: "PREFIX=~/.local REPO_NAME=../gitflow-cjs \
          sh ./contrib/gitflow-installer.sh install stable"
    chdir: ~/.cache/dburke/gitflow-cjs