---
macos_homebrew_formulae:
  - ack
  - coreutils
  - cpanminus
  - ctags
  - htop
  - lpeg
  - luajit
  - neovim
  - node
  - perl
  - ripgrep
  - tmux
  - tree-sitter
  - tree-sitter-cli
macos_homebrew_casks:
  - flameshot
  - macvim
  - font-fira-mono-nerd-font
