---
- name: install dotfiles
  hosts: all
  vars:
    # Assume we're not in a graphical environment, but the graphical role will
    # set this to the correct value if we are
    graphical_environment: false
  roles:
    - role: common
      tags: common
    - role: zsh
      tags: zsh
    - role: hg
      tags: hg
    - role: neovim
      tags: neovim
    - role: vim
      tags: vim
    - role: terminator
      tags: terminator
    - role: tmux
      tags: tmux
    - role: git
      tags: git
