---
- hosts: all
  roles:
    - role: common
      tags: common
    - role: zsh
      tags: zsh
    - role: hg
      tags: hg
    - role: vim
      tags: vim
    - role: tmux
      tags: tmux
    - role: git
      tags: git
