---
- name: install dotfiles
  hosts: all
  roles:
    - role: common
      tags: common
    - role: zsh
      tags: zsh
    - role: hg
      tags: hg
    - role: neovim
      tags: neovim
    - role: vim
      tags: vim
    - role: terminator
      tags: terminator
    - role: tmux
      tags: tmux
    - role: git
      tags: git
