---
- name: upgrade pip and mercurial as user
  ansible.builtin.pip:
    name:
      - pip
      - mercurial
    extra_args: --user --upgrade
- name: install hgflow plugin
  community.general.source_control.hg:
    repo: https://hg.sr.ht/~wu/hgflow
    revision: develop
    dest: ~/.hgext/hgflow
- name: install hg-git via pip as user
  ansible.builtin.pip:
    name: hg-git
    extra_args: --user
- name: symlink hgconfig directory
  ansible.builtin.file:
    path: ~/.hgconfig
    src: "{{ ansible_env.PWD }}/roles/hg/files/hgconfig"
    state: link
- name: symlink hgrc file
  ansible.builtin.file:
    path: ~/.hgrc
    src: "{{ ansible_env.PWD }}/roles/hg/files/hgrc"
    state: link
