---
- name: enable copr repos
  community.general.copr:
    name: "{{ fedora_copr_repos }}"
  become: true
- name: install graphical packages
  ansible.builtin.dnf:
    name: "{{ fedora_graphical_pkgs }}"
  become: true
- name: symlink labwc directory
  ansible.builtin.file:
    path: ~/.config/labwc
    src: "{{ ansible_env.PWD }}/roles/fedora/files/labwc"
    state: link
