---
- name: enable copr repos
  community.general.copr:
    name: "{{ item }}"
  become: true
  with_items: "{{ fedora_copr_repos }}"
- name: install graphical packages
  ansible.builtin.dnf:
    name: "{{ fedora_graphical_pkgs }}"
  become: true
- name: enable systemctl user services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    scope: user
    enabled: true
  with_items:
    - waybar
