---
- name: update existing packages  # noqa: package-latest
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
- name: install dotfiles-specific dnf packages
  ansible.builtin.dnf:
    name: "{{ pkgs }}"
  become: true

- name: check if we're running in a graphical environment
  # the systemctl module doesn't allow running this specific command:
  # https://github.com/ansible/ansible/issues/65785
  ansible.builtin.command:  # noqa: command-instead-of-module
    cmd: systemctl get-default
  register: systemctl_getdefault
  changed_when: "systemctl_getdefault.rc != 0"
- name: run graphical environment tasks
  ansible.builtin.include_tasks: graphical.yml
  when: systemctl_getdefault.stdout == 'graphical.target'
