---
- name: update existing packages  # noqa package-latest
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
- name: install dotfiles-specific dnf packages
  ansible.builtin.dnf:
    name: "{{ pkgs }}"
  become: true
- name: check if we're running in a graphical environment
  ansible.builtin.command: systemctl get-default
  register: systemctl_getdefault
- name: run graphical environment tasks
  include_tasks: graphical.yml
  when: systemctl_getdefault.stdout == 'graphical.target'
