---
- name: update existing packages  # noqa package-latest
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
- name: install dotfiles-specific dnf packages
  ansible.builtin.dnf:
    name: "{{ pkgs }}"
  become: true
