---
- name: symlink .gitconfig
  file:
    path: ~/.gitconfig
    src: "{{ansible_env.PWD}}/roles/git/files/gitconfig"
    state: link
- name: symlink .gitignore
  file:
    path: ~/.gitignore
    src: "{{ansible_env.PWD}}/roles/git/files/gitignore"
    state: link