---
- name: symlink .gitconfig
  ansible.builtin.file:
    path: ~/.gitconfig
    src: "{{ ansible_env.PWD }}/roles/git/files/gitconfig"
    state: link
- name: symlink .gitignore
  ansible.builtin.file:
    path: ~/.gitignore
    src: "{{ ansible_env.PWD }}/roles/git/files/gitignore"
    state: link
- name: touch .gitconfig_local
  ansible.builtin.file:
    path: ~/.gitconfig_local
    state: touch
    mode: 0664
    access_time: preserve
    modification_time: preserve
- name: clone gitflow repo
  ansible.builtin.git:
    repo: https://github.com/petervanderdoes/gitflow-avh.git
    dest: ~/.cache/dburke/gitflow-avh
    version: master
  notify: run gitflow installer