---
- name: symlink .gitconfig
  file:
    path: ~/.gitconfig
    src: "{{ ansible_env.PWD }}/roles/git/files/gitconfig"
    state: link
- name: symlink .gitignore
  file:
    path: ~/.gitignore
    src: "{{ ansible_env.PWD }}/roles/git/files/gitignore"
    state: link
- name: touch .gitconfig_local
  file:
    path: ~/.gitconfig_local
    state: touch
    mode: 0664
    access_time: preserve
    modification_time: preserve
- name: clone gitflow repo
  git:
    repo: https://github.com/petervanderdoes/gitflow-avh.git
    dest: ~/.cache/dburke/gitflow-avh
  register: gitflow_repo
- name: run installer # noqa 301 305
  shell:
    cmd: "PREFIX=~/.local REPO_NAME=../gitflow-avh sh ./contrib/gitflow-installer.sh install stable"
    chdir: ~/.cache/dburke/gitflow-avh
  when: gitflow_repo.changed