return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	branch = "main",
	config = function()
		require("nvim-treesitter").install({
			"bash",
			"comment",
			"css",
			"desktop",
			"diff",
			"dockerfile",
			"git_config",
			"git_rebase",
			"gitcommit",
			"gitignore",
			"hcl",
			"html",
			"ini",
			"java",
			"javadoc",
			"javascript",
			"jinja",
			"jq",
			"json",
			"lua",
			"make",
			"markdown",
			"markdown_inline",
			"nginx",
			"printf",
			"python",
			"readline",
			"regex",
			"requirements",
			"sql",
			"ssh_config",
			"terraform",
			"tmux",
			"toml",
			"udev",
			"vim",
			"vimdoc",
			"xml",
			"xresources",
			"yaml",
		})
	end,
	dependencies = { "gbprod/tree-sitter-gitcommit", "windwp/nvim-ts-autotag", "tadmccorkle/markdown.nvim" },
}
