---
- name: ensure the terminator config directory exists
  ansible.builtin.file:
    path: ~/.config/terminator
    state: directory
    mode: "0755"
- name: symlink terminator config
  ansible.builtin.file:
    path: ~/.config/terminator/config
    src: "{{ ansible_env.PWD }}/roles/terminator/files/config"
    state: link
    mode: "0644"
