return {
	'mileszs/ack.vim',
	'pearofducks/ansible-vim',
	--'closetag',
	--'dbext',
	'tpope/vim-fugitive',
	'dense-analysis/ale',
	'ikirudennis/vim-scratch',
	'jistr/vim-nerdtree-tabs',
	'jnurmine/Zenburn',
	'sjl/gundo.vim',
	'itchyny/lightline.vim',
	'kien/rainbow_parentheses.vim',
	'tpope/vim-repeat',
	'chrisgeo/sparkup',
	'tpope/vim-speeddating',
	'ervandew/supertab',
	'tpope/vim-surround',
	'scrooloose/nerdcommenter',
	'scrooloose/nerdtree',
	--'Toggle',
	'tpope/vim-unimpaired',
	'jceb/vim-orgmode',
	'hashivim/vim-terraform',
	'nvim-tree/nvim-web-devicons',
	'jmcantrell/vim-virtualenv',
	'othree/xml.vim',
	--'YankRing',
	{'L3MON4D3/LuaSnip', build = "make install_jsregexp"},
	'hrsh7th/nvim-cmp',
	'saadparwaiz1/cmp_luasnip',
	{'nvim-telescope/telescope.nvim', dependencies = { 'nvim-lua/plenary.nvim' },
    }
}
