---
- name: update existing packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
- name: install dotfiles-specific dnf packages
  ansible.builtin.dnf:
    name: "{{ fedora_pkgs }}"
  become: true
