---
- name: "do OS-specific tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
      skip: true

- name: upgrade pip as user
  ansible.builtin.pip:
    name:
      - pip
    extra_args: --user --upgrade