---
- name: "do {{ ansible_distribution }}-specific tasks"
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
      skip: true

- name: upgrade pip as user
  ansible.builtin.pip:
    name:
      - pip
    extra_args: --user --upgrade