---
- name: create vim_run directory
  ansible.builtin.file:
    path: ~/.vim_run
    state: directory
    mode: "0775"
- name: symlink .vim directory
  ansible.builtin.file:
    path: ~/.vim
    src: "{{ ansible_env.PWD }}/roles/vim/files/vim"
    state: link
- name: symlink .vimrc
  ansible.builtin.file:
    path: ~/.vimrc
    src: "{{ ansible_env.PWD }}/roles/vim/files/vimrc"
    state: link
- name: create ~/.vim/after/plugin directory
  ansible.builtin.file:
    path: ~/.vim/after/plugin
    state: directory
    mode: "0775"
- name: symlink .gvimrc
  ansible.builtin.file:
    path: ~/.gvimrc
    src: "{{ ansible_env.PWD }}/roles/vim/files/gvimrc"
    state: link
  tags:
    - gvim
    - gui
