---
- name: create vim_run directory
  file:
    path: ~/.vim_run
    state: directory
    mode: 0775
- name: symlink .vim directory
  file:
    path: ~/.vim
    src: "{{ ansible_env.PWD }}/roles/vim/files/vim"
    state: link
- name: symlink .vimrc
  file:
    path: ~/.vimrc
    src: "{{ ansible_env.PWD }}/roles/vim/files/vimrc"
    state: link
- name: create ~/.vim/after/plugin directory
  file:
    path: ~/.vim/after/plugin
    state: directory
    mode: 0775
- name: symlink .gvimrc
  file:
    path: ~/.gvimrc
    src: "{{ ansible_env.PWD }}/roles/vim/files/gvimrc"
    state: link
  tags:
    - gvim
    - gui
