---
# requirements for neovim's `checkhealth` to return healthy status
- name: ensure pynvim has been installed
  ansible.builtin.pip:
    name:
      - pynvim
- name: ensure perl neovim module has been installed
  community.general.cpanm:
    name: Neovim::Ext
    locallib: ~/.local/perl5
    notest: true
- name: clone tfenv
  ansible.builtin.git:
    repo: https://github.com/tfutils/tfenv.git
    dest: ~/.local/share/tfenv
    version: master
- name: symlink tfenv
  ansible.builtin.file:
    path: ~/.local/bin/tfenv
    src: ~/.local/share/tfenv/bin/tfenv
    state: link
- name: symlink terraform
  ansible.builtin.file:
    path: ~/.local/bin/terraform
    src: ~/.local/share/tfenv/bin/terraform
    state: link
# in non-graphical environments, ~/.config won't exist. make sure it does exist
# before we try to symlink anything into it
- name: ensure ~/.config dir exists
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: "0755"
- name: symlink neovim directory
  ansible.builtin.file:
    path: ~/.config/nvim
    src: "{{ ansible_env.PWD }}/roles/neovim/files"
    state: link
